### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by propyless** [gknight007/puppet-panopuppet#1]
Hello!

Without sounding creepy, I've been watching you, and I'd like to introduce myself.
I've seen some of the commits you done on your fork of panopuppet. I was wondering if you were sooner or later going to create a PR for me?

I'd like to ask you a few questions about some of the stuff you have done in the fork as well, you've moved quite a few files and changed some scopes. Is there any particular reason? I'm asking because panopuppet was writing as a project to develop my python skillset and I hadn't worked with django before, so you seem to have some insight that I am perhaps probably missing :).

Thank you for working on a module!

//Propyless

**Comment by gknight007** [comment]
Hi,

It's all good.  I'm glad you noticed.  I was planning on doing a PR soon, but I wasn't done with all my testing.  

The main reason behind the scope move was to allow for panopuppet to build via distutils (https://docs.python.org/2/library/distutils.html). This should allow it to be include in pypi (installable via pip) and allow for RPM targes via `python setup.py bdist_rpm`.

**Comment by propyless** [comment]
Ah alright! Sounds good! Looking forward to it then!
